### ISSUE TITLE
Am I missing something important? How does the lemon-squeezy/webhook route work?

### ISSUE THREAD

**Issue by aiddroid** [lmsqueezy/laravel#88] opened 2024-05-08 12:53 UTC
### Lemon Squeezy for Laravel Version

1.5.3

### Laravel Version

10.4.1

### PHP Version

8.1.0

### Description

How does the /lemon-squeezy/webhook route work? I didn't see any route added to the routes.php file.When I send request to /lemon-squeezy/webhook, it returns 404 not found

### Steps To Reproduce

NA

**Comment by driesvints** [comment] 2024-05-10 10:34
Heya, this is added by the service provider here: https://github.com/lmsqueezy/laravel/blob/main/src/LemonSqueezyServiceProvider.php#L38

How are you sending the request?

**Comment by frankspin89** [comment] 2024-05-20 13:38
Maybe this is related, but when I run php artisan lmsqueezy:listen, I get this error:

```
Route [lemon-squeezy.webhook] not defined.

  at vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:497
    493▕             ! is_null($url = call_user_func($this->missingNamedRouteResolver, $name, $parameters, $absolute))) {
    494▕             return $url;
    495▕         }
    496▕ 
  ➜ 497▕         throw new RouteNotFoundException("Route [{$name}] not defined.");
    498▕     }
    499▕ 
    500▕     /**
    501▕      * Get the URL for a given route instance.

      +17 vendor frames 

  18  artisan:13
  ```

**Comment by driesvints** [comment] 2024-05-21 10:15
@frankspin89 will need a lot more info to reproduce that one...

**Comment by aiddroid** [comment] 2024-05-22 02:04
> Heya, this is added by the service provider here: https://github.com/lmsqueezy/laravel/blob/main/src/LemonSqueezyServiceProvider.php#L38
> 
> How are you sending the request?

Readmd.md updated, https://github.com/lmsqueezy/laravel/pull/89

**Comment by driesvints** [comment] 2024-05-22 11:35
@aiddroid that can't be it because the service provider is autoloaded. You say you use Laravel 10.4.1. Could you please attempt to upgrade to the latest version to see if that helps?

**Comment by driesvints** [comment] 2024-05-27 08:52
Going to close this one now as I don't believe there's an issue atm.

**Closed by driesvints** 2024-05-27 08:52 UTC
Labels: bug
